//spurious table createeee

create table developers (
	name varchar2(30) constraint DEV_NM_NN not null, 
	email_id varchar2(40) constraint DEV_EID_PK primary key,
	password varchar2(20) constraint DEV_PASS_NN not null, 
	imgurl varchar2(200),
	description varchar2(1000) 
);

ALTER TABLE developers ADD MOBILE_NO NUMBER(10 , 0);

CREATE TABLE RGPV_ATTENDANCE (
		ROLL_NO VARCHAR2(20) NOT NULL,
		SUBJ_CODE VARCHAR2(10) NOT NULL,
		WORKING_DATE DATE NOT NULL,
		STATUS NUMBER(1 , 0) NOT NULL
	);

CREATE UNIQUE INDEX RGPVAT_RN_SC_WD_CPK ON RGPV_ATTENDANCE (ROLL_NO ASC, SUBJ_CODE ASC, WORKING_DATE ASC);

ALTER TABLE RGPV_ATTENDANCE ADD CONSTRAINT RGPVAT_RN_SC_WD_CPK PRIMARY KEY (ROLL_NO, SUBJ_CODE, WORKING_DATE);

ALTER TABLE RGPV_ATTENDANCE ADD CONSTRAINT RGPVAT_RN_FK FOREIGN KEY (ROLL_NO)
	REFERENCES RGPV_STUDENTS (ROLL_NO)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

CREATE TABLE RGPV_COLLEGES (
		C_ID VARCHAR2(10) NOT NULL,
		C_NAME VARCHAR2(60) NOT NULL,
		C_LOC VARCHAR2(100) NOT NULL,
		DIRECTOR VARCHAR2(30) NOT NULL,
		EMAIL_ID VARCHAR2(40),
		PASSWORD VARCHAR2(20)
	);

CREATE UNIQUE INDEX RGPVCL_EID_UN ON RGPV_COLLEGES (EMAIL_ID ASC);

CREATE UNIQUE INDEX RGPVCL_CID__PK ON RGPV_COLLEGES (C_ID ASC);

ALTER TABLE RGPV_COLLEGES ADD CONSTRAINT RGPVCL_CID__PK PRIMARY KEY (C_ID);

CREATE TABLE RGPV_COLLEGES_TO_COURSES (
		C_ID VARCHAR2(10) NOT NULL,
		COURSE_ID VARCHAR2(10) NOT NULL,
		SUBCOURSE_ID VARCHAR2(10) NOT NULL,
		D_NO VARCHAR2(10) NOT NULL
	);

CREATE UNIQUE INDEX RGPVCTC_CID_COUID_SCOUID_CPK ON RGPV_COLLEGES_TO_COURSES (C_ID ASC, COURSE_ID ASC, SUBCOURSE_ID ASC);

ALTER TABLE RGPV_COLLEGES_TO_COURSES ADD CONSTRAINT RGPVCTC_CID_COUID_SCOUID_CPK PRIMARY KEY (C_ID, COURSE_ID, SUBCOURSE_ID);

ALTER TABLE RGPV_COLLEGES_TO_COURSES ADD CONSTRAINT RGPVCTC_COUID_SCOUID_FK FOREIGN KEY (COURSE_ID, SUBCOURSE_ID)
	REFERENCES RGPV_SUBCOURSES (COURSE_ID, SUBCOURSE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE RGPV_COLLEGES_TO_COURSES ADD CONSTRAINT RGPVCTC_CID_DNO_FK FOREIGN KEY (C_ID, D_NO)
	REFERENCES RGPV_DEPARTMENTS (C_ID, D_NO)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

CREATE TABLE RGPV_COURSES (
		COURSE_ID VARCHAR2(10) NOT NULL,
		COURSE_NAME VARCHAR2(60) NOT NULL,
		NO_OF_SEM NUMBER(2 , 0) NOT NULL
	);

CREATE UNIQUE INDEX RGPVCO_COUID_PK ON RGPV_COURSES (COURSE_ID ASC);

ALTER TABLE RGPV_COURSES ADD CONSTRAINT RGPVCO_COUID_PK PRIMARY KEY (COURSE_ID);

CREATE TABLE RGPV_DEPARTMENTS (
		C_ID VARCHAR2(10) NOT NULL,
		D_NO VARCHAR2(10) NOT NULL,
		D_NAME VARCHAR2(50) NOT NULL,
		HOD VARCHAR2(30) NOT NULL,
		PASSWORD VARCHAR2(20) NOT NULL,
		MOBILE_NO NUMBER(10 , 0),
		EMAIL_ID VARCHAR2(40),
		NO_OF_STUDENT NUMBER(3 , 0) NOT NULL,
		NO_OF_FACULTY NUMBER(2 , 0) NOT NULL
	);

CREATE UNIQUE INDEX RGPVD_CID_DNO_CPK ON RGPV_DEPARTMENTS (C_ID ASC, D_NO ASC);

CREATE UNIQUE INDEX RGPVD_EID_UN ON RGPV_DEPARTMENTS (EMAIL_ID ASC);

CREATE UNIQUE INDEX RGPVD_MOB_UN ON RGPV_DEPARTMENTS (MOBILE_NO ASC);

ALTER TABLE RGPV_DEPARTMENTS ADD CONSTRAINT RGPVD_CID_DNO_CPK PRIMARY KEY (C_ID, D_NO);

ALTER TABLE RGPV_DEPARTMENTS ADD CONSTRAINT RGPVD_CID_FK FOREIGN KEY (C_ID)
	REFERENCES RGPV_COLLEGES (C_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
CREATE TABLE RGPV_FACULTIES (
		FACULTY_ID VARCHAR2(20) NOT NULL,
		FACULTY_NAME VARCHAR2(30) NOT NULL,
		PASSWORD VARCHAR2(20) NOT NULL,
		C_ID VARCHAR2(10) NOT NULL,
		D_NO VARCHAR2(10) NOT NULL,
		MOBILE_NO NUMBER(10 , 0),
		EMAIL_ID VARCHAR2(40)
	);

CREATE UNIQUE INDEX RGPVF_MOB_UN ON RGPV_FACULTIES (MOBILE_NO ASC);

CREATE UNIQUE INDEX RGPVF_FID_PK ON RGPV_FACULTIES (FACULTY_ID ASC);

CREATE UNIQUE INDEX RGPVF_EID_UN ON RGPV_FACULTIES (EMAIL_ID ASC);

ALTER TABLE RGPV_FACULTIES ADD CONSTRAINT RGPVF_FID_PK PRIMARY KEY (FACULTY_ID);

ALTER TABLE RGPV_FACULTIES ADD CONSTRAINT RGPVF_CID_DNO_FK FOREIGN KEY (C_ID, D_NO)
	REFERENCES RGPV_DEPARTMENTS (C_ID, D_NO)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;


CREATE TABLE RGPV_NOTICE_BOARD (
		IMGURL VARCHAR2(200) NOT NULL,
		TITLE VARCHAR2(200) NOT NULL,
		DESCRIPTION VARCHAR2(1000) NOT NULL,
		START_DATE DATE NOT NULL,
		DAYS NUMBER(2 , 0),
		EVENT_DATE DATE,
		HOST_CLG VARCHAR2(10)
	);

CREATE TABLE RGPV_STUDENTS (
		ROLL_NO VARCHAR2(20) NOT NULL,
		STUDENT_NAME VARCHAR2(30) NOT NULL,
		C_ID VARCHAR2(10) NOT NULL,
		COURSE_ID VARCHAR2(10) NOT NULL,
		SUBCOURSE_ID VARCHAR2(10) NOT NULL,
		MOBILE_NO NUMBER(10 , 0),
		EMAIL_ID VARCHAR2(40),
		BATCH_YR NUMBER(4 , 0) NOT NULL,
		SEM NUMBER(2 , 0) NOT NULL,
		CLASS CHAR(1) NOT NULL
	);

CREATE UNIQUE INDEX RGPVST_EID_UN ON RGPV_STUDENTS (EMAIL_ID ASC);

CREATE UNIQUE INDEX RGPVST_RN_PK ON RGPV_STUDENTS (ROLL_NO ASC);

CREATE UNIQUE INDEX RGPVST_MOB_UN ON RGPV_STUDENTS (MOBILE_NO ASC);

ALTER TABLE RGPV_STUDENTS ADD CONSTRAINT RGPVST_RN_PK PRIMARY KEY (ROLL_NO);

ALTER TABLE RGPV_STUDENTS ADD CONSTRAINT RGPVST_CID_COUID_SCOUID_FK FOREIGN KEY (C_ID, COURSE_ID, SUBCOURSE_ID)
	REFERENCES RGPV_COLLEGES_TO_COURSES (C_ID, COURSE_ID, SUBCOURSE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;
CREATE TABLE RGPV_SUBCOURSES (
		COURSE_ID VARCHAR2(10) NOT NULL,
		SUBCOURSE_ID VARCHAR2(10) NOT NULL,
		SUBCOURSE_NAME VARCHAR2(60) NOT NULL
	);

CREATE UNIQUE INDEX RGPVSCO_COUID_SCOUID_CPK ON RGPV_SUBCOURSES (COURSE_ID ASC, SUBCOURSE_ID ASC);

ALTER TABLE RGPV_SUBCOURSES ADD CONSTRAINT RGPVSCO_COUID_SCOUID_CPK PRIMARY KEY (COURSE_ID, SUBCOURSE_ID);

ALTER TABLE RGPV_SUBCOURSES ADD CONSTRAINT RGPVSCO_COUID_FK FOREIGN KEY (COURSE_ID)
	REFERENCES RGPV_COURSES (COURSE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

CREATE TABLE RGPV_SUBJ_TO_FACULTY (
		C_ID VARCHAR2(10) NOT NULL,
		COURSE_ID VARCHAR2(10) NOT NULL,
		SUBCOURSE_ID VARCHAR2(10) NOT NULL,
		SUBJ_CODE VARCHAR2(10) NOT NULL,
		CLASS CHAR(1) NOT NULL,
		FACULTY_ID VARCHAR2(20) NOT NULL
	);

CREATE UNIQUE INDEX RGPVSTF_CID_COID_SID_SC_CL_CPK ON RGPV_SUBJ_TO_FACULTY (C_ID ASC, COURSE_ID ASC, SUBCOURSE_ID ASC, SUBJ_CODE ASC, CLASS ASC);

ALTER TABLE RGPV_SUBJ_TO_FACULTY ADD CONSTRAINT RGPVSTF_CID_COID_SID_SC_CL_CPK PRIMARY KEY (C_ID, COURSE_ID, SUBCOURSE_ID, SUBJ_CODE, CLASS);

ALTER TABLE RGPV_SUBJ_TO_FACULTY ADD CONSTRAINT RGPVSTF_COUID_SCOUID_SC_FK FOREIGN KEY (COURSE_ID, SUBCOURSE_ID, SUBJ_CODE)
	REFERENCES RGPV_SUBJECTS (COURSE_ID, SUBCOURSE_ID, SUBJ_CODE)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

ALTER TABLE RGPV_SUBJ_TO_FACULTY ADD CONSTRAINT RGPVSTF_CID_COUID_SCOUID_FK FOREIGN KEY (C_ID, COURSE_ID, SUBCOURSE_ID)
	REFERENCES RGPV_COLLEGES_TO_COURSES (C_ID, COURSE_ID, SUBCOURSE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;


CREATE TABLE RGPV_SUBJECTS (
		COURSE_ID VARCHAR2(10) NOT NULL,
		SUBCOURSE_ID VARCHAR2(10) NOT NULL,
		SUBJ_CODE VARCHAR2(10) NOT NULL,
		SUBJ_NAME VARCHAR2(50) NOT NULL,
		SEM NUMBER(2 , 0) NOT NULL
	);

CREATE UNIQUE INDEX RGPVSB_COUID_SCOUID_SC_CPK ON RGPV_SUBJECTS (COURSE_ID ASC, SUBCOURSE_ID ASC, SUBJ_CODE ASC);

ALTER TABLE RGPV_SUBJECTS ADD CONSTRAINT RGPVSB_COUID_SCOUID_SC_CPK PRIMARY KEY (COURSE_ID, SUBCOURSE_ID, SUBJ_CODE);

ALTER TABLE RGPV_SUBJECTS ADD CONSTRAINT RGPVSB_COUID_SCOUID_FK FOREIGN KEY (COURSE_ID, SUBCOURSE_ID)
	REFERENCES RGPV_SUBCOURSES (COURSE_ID, SUBCOURSE_ID)
	ON DELETE RESTRICT
	ON UPDATE CASCADE;

CREATE TABLE UNIVERSITY (
		U_ID VARCHAR2(10) NOT NULL,
		U_NAME VARCHAR2(60) NOT NULL,
		U_LOC VARCHAR2(100) NOT NULL,
		COURSE_TABLE VARCHAR2(30) NOT NULL,
		SUBCOURSE_TABLE VARCHAR2(30) NOT NULL,
		COLLEGE_TABLE VARCHAR2(30) NOT NULL,
		DEPT_TABLE VARCHAR2(30) NOT NULL,
		STUDENT_TABLE VARCHAR2(30) NOT NULL,
		FACULTY_TABLE VARCHAR2(30) NOT NULL,
		CTC_TABLE VARCHAR2(30) NOT NULL,
		SUBJECT_TABLE VARCHAR2(30) NOT NULL,
		STF_TABLE VARCHAR2(30) NOT NULL,
		ATTENDANCE_TABLE VARCHAR2(30) NOT NULL,
		STATE VARCHAR2(20) NOT NULL
	);

CREATE UNIQUE INDEX UN_ST_UN ON UNIVERSITY (STUDENT_TABLE ASC);

CREATE UNIQUE INDEX UN_AT_UN ON UNIVERSITY (ATTENDANCE_TABLE ASC);

CREATE UNIQUE INDEX UN_CTCT_UN ON UNIVERSITY (CTC_TABLE ASC);

CREATE UNIQUE INDEX UN_SBT_UN ON UNIVERSITY (SUBJECT_TABLE ASC);

CREATE UNIQUE INDEX UN_STFT_UN ON UNIVERSITY (STF_TABLE ASC);

CREATE UNIQUE INDEX UN_SCOT_UN ON UNIVERSITY (SUBCOURSE_TABLE ASC);

CREATE UNIQUE INDEX UN_CT_UN ON UNIVERSITY (COLLEGE_TABLE ASC);

CREATE UNIQUE INDEX UN_COT_UN ON UNIVERSITY (COURSE_TABLE ASC);

CREATE UNIQUE INDEX UN_UID_PK ON UNIVERSITY (U_ID ASC);

CREATE UNIQUE INDEX UN_DT_UN ON UNIVERSITY (DEPT_TABLE ASC);

CREATE UNIQUE INDEX UN_FT_UN ON UNIVERSITY (FACULTY_TABLE ASC);

ALTER TABLE UNIVERSITY ADD CONSTRAINT UN_UID_PK PRIMARY KEY (U_ID);